server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://${DB_PROXY_HOST}/webthuetro_users
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

