server:
  port: 8080

spring:

  datasource:
    url: jdbc:mysql://${DB_HOST}/?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver


  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_API}
              predicates:
                - Path=/api/auth/**,/api/oauth2/**
            - id: user-service
              uri: ${USER_API}
              predicates:
                - Path=/api/user/**
            - id: file-service
              uri: ${FILE_API}
              predicates:
                - Path=/api/image/**



